#spring:
#  datasource:
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false